# Análise de Atendimentos

Este notebook será utilizado para exploração, análise e visualização
dos dados de atendimentos médicos do projeto.

As análises realizadas neste notebook têm finalidade educacional.

In [116]:
import pandas as pd

In [117]:
df = pd.read_csv("../data/raw/atendimentos.csv")

In [118]:
df

,id,nome,idade,cidade,especialidade,status,email,telefone
0,1,Bruno Lima,30.0,Vinhedo,Clinico Geral,Concluido,bruno.lima@email.com,11999990001
1,2,Ana Souza,NaN,Campinas,Cardiologia,Agendado,ana.souza@email.com,11999990002
2,3,Carlos Mendes,40.0,Jundiai,Ortopedia,Cancelado,carlos.mendes@email.com,11999990003
3,4,Mariana Silva,35.0,Valinhos,Pediatria,Concluido,mariana.silva@email.com,11999990004
4,5,Joao Santos,52.0,Campinas,Cardiologia,Concluido,joao.santos@email.com,11999990005
5,5,Joao Santos,52.0,Campinas,Cardiologia,Concluido,joao.santos@email.com,11999990005
6,6,Pedro Oliveira,28.0,Campinas,Cardiologia,concluido,pedro.oliveira@email.com,11999990006
7,7,Juliana Costa,45.0,CAMPINAS,cardiologia,AGENDADO,juliana.costa@email.com,11999990007
8,8,Marcos Pereira,67.0,Campinas,ORTOPEDIA,Cancelado,marcos.pereira@email.com,11999990008
9,9,Fernanda Alves,29.0,Vinhedo,Dermatologia,Concluido,fernanda.alves@email.com,11999990009
10,10,Rafael Souza,NaN,Jundiai,Cardiologia,agendado,rafael.souza@email.com,11999990010
11,11,Patricia Lima,38.0,Campinas,Pediatria,CONCLUIDO,patricia.lima@email.com,11999990011
12,12,Gabriel Santos,150.0,Valinhos,Ortopedia,Concluido,gabriel.santos@email.com,11999990012
13,13,Beatriz Oliveira,22.0,Vinhedo,Dermatologia,Cancelado,beatriz.oliveira@email.com,11999990013
14,14,Lucas Ferreira,41.0,Campinas,Cardiologia,Agendado,lucas.ferreira@email.com,11999990014
15,15,Amanda Rodrigues,34.0,Campinas,Pediatria,Concluido,amanda.rodrigues@email.com,11999990015
16,16,Diego Martins,39.0,JUNDIAI,Ortopedia,concluido,diego.martins@email.com,11999990016
17,17,Carolina Gomes,27.0,Valinhos,Dermatologia,Cancelado,carolina.gomes@email.com,11999990017
18,18,Thiago Alves,63.0,Campinas,Cardiologia,Concluido,thiago.alves@email.com,11999990018
19,19,Julio Santos,-5.0,Vinhedo,Clinico Geral,Agendado,julio.santos@email.com,11999990019
20,20,Renata Costa,31.0,Campinas,Pediatria,Concluido,renata.costa@email.com,11999990020
21,21,Mariana Silva,35.0,Valinhos,Pediatria,Concluido,mariana.silva@email.com,11999990004
22,22,Roberto Lima,49.0,Campinas,Cardiologia,Cancelado,roberto.lima@email.com,11999990021
23,23,Isabela Mendes,26.0,Vinhedo,Dermatologia,Agendado,isabela.mendes@email.com,11999990022
24,24,Daniel Souza,58.0,Campinas,Cardiologia,Concluido,daniel.souza@email.com,11999990023
25,25,Vanessa Oliveira,NaN,Valinhos,Pediatria,Agendado,vanessa.oliveira@email.com,11999990024
26,26,Andre Pereira,36.0,Campinas,Ortopedia,Concluido,andre.pereira@email.com,11999990025
27,27,Paula Fernandes,43.0,Vinhedo,Dermatologia,CONCLUIDO,paula.fernandes@email.com,11999990026
28,28,Mateus Costa,19.0,Campinas,Clinico Geral,Cancelado,mateus.costa@email.com,11999990027
29,29,Lucas Ferreira,41.0,Campinas,Cardiologia,Agendado,lucas.ferreira@email.com,11999990014
30,30,Joana Alves,33.0,Valinhos,Pediatria,Concluido,joana.alves@email.com,11999990028

In [119]:
df.shape

(31, 8)

In [120]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             31 non-null     int64
 1   nome           31 non-null     str
 2   idade          28 non-null     float64
 3   cidade         31 non-null     str
 4   especialidade  31 non-null     str
 5   status         31 non-null     str
 6   email          31 non-null     str
 7   telefone       31 non-null     int64
dtypes: float64(1), int64(2), str(5)
memory usage: 2.1 KB

In [121]:
df.describe()

              id       idade      telefone
count  31.000000   28.000000  3.100000e+01
mean   15.161290   41.357143  1.199999e+10
std     8.858505   25.670583  8.193887e+00
min     1.000000   -5.000000  1.199999e+10
25%     7.500000   29.750000  1.199999e+10
50%    15.000000   37.000000  1.199999e+10
75%    22.500000   46.000000  1.199999e+10
max    30.000000  150.000000  1.199999e+10

In [122]:
df.isnull().sum()

id               0
nome             0
idade            3
cidade           0
especialidade    0
status           0
email            0
telefone         0
dtype: int64

In [123]:
df["status"].unique()

<StringArray>
['Concluido',  'Agendado', 'Cancelado', 'concluido',  'AGENDADO',  'agendado',
 'CONCLUIDO']
Length: 7, dtype: str

In [124]:
df["status"].value_counts()

status
Concluido    13
Agendado      6
Cancelado     6
concluido     2
CONCLUIDO     2
AGENDADO      1
agendado      1
Name: count, dtype: int64

In [125]:
df["especialidade"].value_counts()

especialidade
Cardiologia      10
Pediatria         6
Dermatologia      5
Ortopedia         4
Clinico Geral     3
cardiologia       1
ORTOPEDIA         1
 Pediatria        1
Name: count, dtype: int64

In [126]:
df["cidade"].value_counts()

cidade
Campinas      13
Vinhedo        6
Valinhos       5
Jundiai        2
 Valinhos      1
CAMPINAS       1
 Campinas      1
 Campinas      1
JUNDIAI        1
Name: count, dtype: int64

In [127]:
len(df)

31

In [128]:
df["idade"].mean()

np.float64(41.357142857142854)

In [129]:
df["idade"].min()

np.float64(-5.0)

In [130]:
df["idade"].max()

np.float64(150.0)

In [131]:
df[df["idade"].isnull()]

,id,nome,idade,cidade,especialidade,status,email,telefone
1,2,Ana Souza,NaN,Campinas,Cardiologia,Agendado,ana.souza@email.com,11999990002
10,10,Rafael Souza,NaN,Jundiai,Cardiologia,agendado,rafael.souza@email.com,11999990010
25,25,Vanessa Oliveira,NaN,Valinhos,Pediatria,Agendado,vanessa.oliveira@email.com,11999990024

In [132]:
df["idade"].median()

np.float64(37.0)

In [133]:
df["idade"] = df["idade"].fillna(df["idade"].median())

In [134]:
df[df["idade"] > 100]

,id,nome,idade,cidade,especialidade,status,email,telefone
12,12,Gabriel Santos,150.0,Valinhos,Ortopedia,Concluido,gabriel.santos@email.com,11999990012

In [135]:
df[df["idade"] < 0]

,id,nome,idade,cidade,especialidade,status,email,telefone
19,19,Julio Santos,-5.0,Vinhedo,Clinico Geral,Agendado,julio.santos@email.com,11999990019

In [136]:
df[(df["idade"] < 0) | (df["idade"] > 100)]

,id,nome,idade,cidade,especialidade,status,email,telefone
12,12,Gabriel Santos,150.0,Valinhos,Ortopedia,Concluido,gabriel.santos@email.com,11999990012
19,19,Julio Santos,-5.0,Vinhedo,Clinico Geral,Agendado,julio.santos@email.com,11999990019

In [137]:
df.loc[(df["idade"] < 0) | (df["idade"] > 100), "idade"] = pd.NA

In [138]:
df["cidade"].unique()

<StringArray>
[   'Vinhedo',   'Campinas',    'Jundiai', ' Valinhos ',   'CAMPINAS',
 ' Campinas ',   'Valinhos',  ' Campinas',    'JUNDIAI']
Length: 9, dtype: str

In [139]:
df["cidade"] = df["cidade"].str.strip()

In [140]:
df["cidade"] = df["cidade"].str.lower()

In [141]:
df["especialidade"] = df["especialidade"].str.strip()

In [142]:
df["especialidade"] = df["especialidade"].str.lower()

In [143]:
df["especialidade"].unique()

<StringArray>
['clinico geral', 'cardiologia', 'ortopedia', 'pediatria', 'dermatologia']
Length: 5, dtype: str

In [144]:
df["status"] = df["status"].str.strip()

In [145]:
df["status"] = df["status"].str.lower()

In [146]:
df["status"].unique()

<StringArray>
['concluido', 'agendado', 'cancelado']
Length: 3, dtype: str

In [147]:
df[df["email"].duplicated(keep=False)]

,id,nome,idade,cidade,especialidade,status,email,telefone
4,5,Joao Santos,52.0,campinas,cardiologia,concluido,joao.santos@email.com,11999990005
5,5,Joao Santos,52.0,campinas,cardiologia,concluido,joao.santos@email.com,11999990005
14,14,Lucas Ferreira,41.0,campinas,cardiologia,agendado,lucas.ferreira@email.com,11999990014
29,29,Lucas Ferreira,41.0,campinas,cardiologia,agendado,lucas.ferreira@email.com,11999990014

In [149]:
df[df["telefone"].duplicated(keep=False)]

,id,nome,idade,cidade,especialidade,status,email,telefone
3,4,Mariana Silva,35.0,valinhos,pediatria,concluido,mariana.silva@email.com,11999990004
4,5,Joao Santos,52.0,campinas,cardiologia,concluido,joao.santos@email.com,11999990005
5,5,Joao Santos,52.0,campinas,cardiologia,concluido,joao.santos@email.com,11999990005
14,14,Lucas Ferreira,41.0,campinas,cardiologia,agendado,lucas.ferreira@email.com,11999990014
21,21,Mariana Silva,35.0,valinhos,pediatria,concluido,mariana.silva@email.com,11999990004
29,29,Lucas Ferreira,41.0,campinas,cardiologia,agendado,lucas.ferreira@email.com,11999990014

In [74]:
df = df.drop_duplicates(subset="email")

In [150]:
df.drop_duplicates(subset="email", keep="first")

,id,nome,idade,cidade,especialidade,status,email,telefone
0,1,Bruno Lima,30.0,vinhedo,clinico geral,concluido,bruno.lima@email.com,11999990001
1,2,Ana Souza,37.0,campinas,cardiologia,agendado,ana.souza@email.com,11999990002
2,3,Carlos Mendes,40.0,jundiai,ortopedia,cancelado,carlos.mendes@email.com,11999990003
3,4,Mariana Silva,35.0,valinhos,pediatria,concluido,mariana.silva@email.com,11999990004
4,5,Joao Santos,52.0,campinas,cardiologia,concluido,joao.santos@email.com,11999990005
6,6,Pedro Oliveira,28.0,campinas,cardiologia,concluido,pedro.oliveira@email.com,11999990006
7,7,Juliana Costa,45.0,campinas,cardiologia,agendado,juliana.costa@email.com,11999990007
8,8,Marcos Pereira,67.0,campinas,ortopedia,cancelado,marcos.pereira@email.com,11999990008
9,9,Fernanda Alves,29.0,vinhedo,dermatologia,concluido,fernanda.alves@email.com,11999990009
10,10,Rafael Souza,37.0,jundiai,cardiologia,agendado,rafael.souza@email.com,11999990010
11,11,Patricia Lima,38.0,campinas,pediatria,concluido,patricia.lima@email.com,11999990011
12,12,Gabriel Santos,NaN,valinhos,ortopedia,concluido,gabriel.santos@email.com,11999990012
13,13,Beatriz Oliveira,22.0,vinhedo,dermatologia,cancelado,beatriz.oliveira@email.com,11999990013
14,14,Lucas Ferreira,41.0,campinas,cardiologia,agendado,lucas.ferreira@email.com,11999990014
15,15,Amanda Rodrigues,34.0,campinas,pediatria,concluido,amanda.rodrigues@email.com,11999990015
16,16,Diego Martins,39.0,jundiai,ortopedia,concluido,diego.martins@email.com,11999990016
17,17,Carolina Gomes,27.0,valinhos,dermatologia,cancelado,carolina.gomes@email.com,11999990017
18,18,Thiago Alves,63.0,campinas,cardiologia,concluido,thiago.alves@email.com,11999990018
19,19,Julio Santos,NaN,vinhedo,clinico geral,agendado,julio.santos@email.com,11999990019
20,20,Renata Costa,31.0,campinas,pediatria,concluido,renata.costa@email.com,11999990020
21,21,Mariana Silva,35.0,valinhos,pediatria,concluido,mariana.silva@email.com,11999990004
22,22,Roberto Lima,49.0,campinas,cardiologia,cancelado,roberto.lima@email.com,11999990021
23,23,Isabela Mendes,26.0,vinhedo,dermatologia,agendado,isabela.mendes@email.com,11999990022
24,24,Daniel Souza,58.0,campinas,cardiologia,concluido,daniel.souza@email.com,11999990023
25,25,Vanessa Oliveira,37.0,valinhos,pediatria,agendado,vanessa.oliveira@email.com,11999990024
26,26,Andre Pereira,36.0,campinas,ortopedia,concluido,andre.pereira@email.com,11999990025
27,27,Paula Fernandes,43.0,vinhedo,dermatologia,concluido,paula.fernandes@email.com,11999990026
28,28,Mateus Costa,19.0,campinas,clinico geral,cancelado,mateus.costa@email.com,11999990027
30,30,Joana Alves,33.0,valinhos,pediatria,concluido,joana.alves@email.com,11999990028