# Análise de Atendimentos

Este notebook será utilizado para exploração, análise e visualização
dos dados de atendimentos médicos do projeto.

As análises realizadas neste notebook têm finalidade educacional.

In [ ]:
import pandas as pd  # Importa a biblioteca Pandas para manipulação e análise dos dados

In [ ]:
df = pd.read_csv("../data/raw/atendimentos.csv")  # Carrega o arquivo CSV bruto e armazena os dados em um DataFrame

In [ ]:
df  # Exibe todos os registros da base de dados

,id,nome,idade,cidade,especialidade,status,email,telefone
0,1,Bruno Lima,30.0,Vinhedo,Clinico Geral,Concluido,bruno.lima@email.com,11999990001
1,2,Ana Souza,NaN,Campinas,Cardiologia,Agendado,ana.souza@email.com,11999990002
2,3,Carlos Mendes,40.0,Jundiai,Ortopedia,Cancelado,carlos.mendes@email.com,11999990003
3,4,Mariana Silva,35.0,Valinhos,Pediatria,Concluido,mariana.silva@email.com,11999990004
4,5,Joao Santos,52.0,Campinas,Cardiologia,Concluido,joao.santos@email.com,11999990005
5,5,Joao Santos,52.0,Campinas,Cardiologia,Concluido,joao.santos@email.com,11999990005
6,6,Pedro Oliveira,28.0,Campinas,Cardiologia,concluido,pedro.oliveira@email.com,11999990006
7,7,Juliana Costa,45.0,CAMPINAS,cardiologia,AGENDADO,juliana.costa@email.com,11999990007
8,8,Marcos Pereira,67.0,Campinas,ORTOPEDIA,Cancelado,marcos.pereira@email.com,11999990008
9,9,Fernanda Alves,29.0,Vinhedo,Dermatologia,Concluido,fernanda.alves@email.com,11999990009
10,10,Rafael Souza,NaN,Jundiai,Cardiologia,agendado,rafael.souza@email.com,11999990010
11,11,Patricia Lima,38.0,Campinas,Pediatria,CONCLUIDO,patricia.lima@email.com,11999990011
12,12,Gabriel Santos,150.0,Valinhos,Ortopedia,Concluido,gabriel.santos@email.com,11999990012
13,13,Beatriz Oliveira,22.0,Vinhedo,Dermatologia,Cancelado,beatriz.oliveira@email.com,11999990013
14,14,Lucas Ferreira,41.0,Campinas,Cardiologia,Agendado,lucas.ferreira@email.com,11999990014
15,15,Amanda Rodrigues,34.0,Campinas,Pediatria,Concluido,amanda.rodrigues@email.com,11999990015
16,16,Diego Martins,39.0,JUNDIAI,Ortopedia,concluido,diego.martins@email.com,11999990016
17,17,Carolina Gomes,27.0,Valinhos,Dermatologia,Cancelado,carolina.gomes@email.com,11999990017
18,18,Thiago Alves,63.0,Campinas,Cardiologia,Concluido,thiago.alves@email.com,11999990018
19,19,Julio Santos,-5.0,Vinhedo,Clinico Geral,Agendado,julio.santos@email.com,11999990019
20,20,Renata Costa,31.0,Campinas,Pediatria,Concluido,renata.costa@email.com,11999990020
21,21,Mariana Silva,35.0,Valinhos,Pediatria,Concluido,mariana.silva@email.com,11999990004
22,22,Roberto Lima,49.0,Campinas,Cardiologia,Cancelado,roberto.lima@email.com,11999990021
23,23,Isabela Mendes,26.0,Vinhedo,Dermatologia,Agendado,isabela.mendes@email.com,11999990022
24,24,Daniel Souza,58.0,Campinas,Cardiologia,Concluido,daniel.souza@email.com,11999990023
25,25,Vanessa Oliveira,NaN,Valinhos,Pediatria,Agendado,vanessa.oliveira@email.com,11999990024
26,26,Andre Pereira,36.0,Campinas,Ortopedia,Concluido,andre.pereira@email.com,11999990025
27,27,Paula Fernandes,43.0,Vinhedo,Dermatologia,CONCLUIDO,paula.fernandes@email.com,11999990026
28,28,Mateus Costa,19.0,Campinas,Clinico Geral,Cancelado,mateus.costa@email.com,11999990027
29,29,Lucas Ferreira,41.0,Campinas,Cardiologia,Agendado,lucas.ferreira@email.com,11999990014
30,30,Joana Alves,33.0,Valinhos,Pediatria,Concluido,joana.alves@email.com,11999990028

In [ ]:
df.shape  # Quantas linhas e colunas existem na nossa base?

(31, 8)

In [ ]:
df.info()  # Quais são os tipos de dados e a quantidade de valores preenchidos em cada coluna?

<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             31 non-null     int64
 1   nome           31 non-null     str
 2   idade          28 non-null     float64
 3   cidade         31 non-null     str
 4   especialidade  31 non-null     str
 5   status         31 non-null     str
 6   email          31 non-null     str
 7   telefone       31 non-null     int64
dtypes: float64(1), int64(2), str(5)
memory usage: 2.1 KB

In [ ]:
df.describe()  # Qual é o resumo estatístico das colunas numéricas da nossa base?

              id       idade      telefone
count  31.000000   28.000000  3.100000e+01
mean   15.161290   41.357143  1.199999e+10
std     8.858505   25.670583  8.193887e+00
min     1.000000   -5.000000  1.199999e+10
25%     7.500000   29.750000  1.199999e+10
50%    15.000000   37.000000  1.199999e+10
75%    22.500000   46.000000  1.199999e+10
max    30.000000  150.000000  1.199999e+10

In [ ]:
df.isnull().sum()  # Quantos valores ausentes existem em cada coluna da nossa base?

id               0
nome             0
idade            3
cidade           0
especialidade    0
status           0
email            0
telefone         0
dtype: int64

In [ ]:
df["status"].unique()  # Quais são os diferentes status existentes na nossa base?

<StringArray>
['Concluido',  'Agendado', 'Cancelado', 'concluido',  'AGENDADO',  'agendado',
 'CONCLUIDO']
Length: 7, dtype: str

In [ ]:
df["status"].value_counts()  # Qual é o status mais frequente na nossa base?

status
Concluido    13
Agendado      6
Cancelado     6
concluido     2
CONCLUIDO     2
AGENDADO      1
agendado      1
Name: count, dtype: int64

In [ ]:
df["especialidade"].value_counts()  # Qual especialidade possui mais registros na nossa base?

especialidade
Cardiologia      10
Pediatria         6
Dermatologia      5
Ortopedia         4
Clinico Geral     3
cardiologia       1
ORTOPEDIA         1
 Pediatria        1
Name: count, dtype: int64

In [ ]:
df["cidade"].value_counts()  # Qual cidade possui mais registros na nossa base?

cidade
Campinas      13
Vinhedo        6
Valinhos       5
Jundiai        2
 Valinhos      1
CAMPINAS       1
 Campinas      1
 Campinas      1
JUNDIAI        1
Name: count, dtype: int64

In [ ]:
len(df)  # Quantos registros existem na nossa base?

31

In [ ]:
df["idade"].mean()  # Qual é a idade média dos pacientes?

np.float64(41.357142857142854)

In [ ]:
df["idade"].min()  # Qual é a menor idade registrada na nossa base?

np.float64(-5.0)

In [ ]:
df["idade"].max()  # Qual é a maior idade registrada na nossa base?

np.float64(150.0)

In [ ]:
df[df["idade"].isnull()]  # Quais registros possuem valores ausentes na coluna idade?

Empty DataFrame
Columns: [id, nome, idade, cidade, especialidade, status, email, telefone]
Index: []

In [ ]:
df["idade"].median()  # Qual é a idade mediana dos pacientes?

np.float64(37.0)

In [ ]:
df["idade"] = df["idade"].fillna(df["idade"].median())  # Como preencher os valores ausentes de idade usando a mediana?

In [ ]:
df[df["idade"] > 100]  # Existem pacientes com idade superior a 100 anos?

,id,nome,idade,cidade,especialidade,status,email,telefone
12,12,Gabriel Santos,150.0,Valinhos,Ortopedia,Concluido,gabriel.santos@email.com,11999990012

In [ ]:
df[df["idade"] < 0]  # Existem registros com idade menor que zero?

,id,nome,idade,cidade,especialidade,status,email,telefone
19,19,Julio Santos,-5.0,Vinhedo,Clinico Geral,Agendado,julio.santos@email.com,11999990019

In [ ]:
df[(df["idade"] < 0) | (df["idade"] > 100)]  # Existem registros com idade inválida, menor que 0 ou maior que 100?

,id,nome,idade,cidade,especialidade,status,email,telefone
12,12,Gabriel Santos,150.0,Valinhos,Ortopedia,Concluido,gabriel.santos@email.com,11999990012
19,19,Julio Santos,-5.0,Vinhedo,Clinico Geral,Agendado,julio.santos@email.com,11999990019

In [ ]:
df.loc[(df["idade"] < 0) | (df["idade"] > 100), "idade"] = pd.NA  # Substitui as idades inválidas por valores ausentes

In [ ]:
df["cidade"].unique()  # Quais são os diferentes valores de cidade existentes na nossa base?

<StringArray>
[   'Vinhedo',   'Campinas',    'Jundiai', ' Valinhos ',   'CAMPINAS',
 ' Campinas ',   'Valinhos',  ' Campinas',    'JUNDIAI']
Length: 9, dtype: str

In [ ]:
df["cidade"] = df["cidade"].str.strip()  # Remove espaços extras no início e no final dos nomes das cidades

In [ ]:
df["cidade"] = df["cidade"].str.lower()  # Padroniza os nomes das cidades para letras minúsculas

In [ ]:
df["especialidade"] = df["especialidade"].str.strip()  # Remove espaços extras no início e no final das especialidades

In [ ]:
df["especialidade"] = df["especialidade"].str.lower()  # Padroniza os nomes das especialidades para letras minúsculas

In [ ]:
df["especialidade"].unique()  # Quais são os diferentes valores de especialidade existentes na nossa base?

<StringArray>
['clinico geral', 'cardiologia', 'ortopedia', 'pediatria', 'dermatologia']
Length: 5, dtype: str

In [ ]:
df["status"] = df["status"].str.strip()  # Remove espaços extras no início e no final dos status

In [ ]:
df["status"] = df["status"].str.lower()  # Padroniza os valores de status para letras minúsculas

In [ ]:
df["status"].unique()  # Quais são os diferentes valores de status existentes na nossa base?

<StringArray>
['concluido', 'agendado', 'cancelado']
Length: 3, dtype: str

In [ ]:
df[df["email"].duplicated(keep=False)]  # Quais registros possuem emails duplicados na nossa base?

,id,nome,idade,cidade,especialidade,status,email,telefone
4,5,Joao Santos,52.0,campinas,cardiologia,concluido,joao.santos@email.com,11999990005
5,5,Joao Santos,52.0,campinas,cardiologia,concluido,joao.santos@email.com,11999990005
14,14,Lucas Ferreira,41.0,campinas,cardiologia,agendado,lucas.ferreira@email.com,11999990014
29,29,Lucas Ferreira,41.0,campinas,cardiologia,agendado,lucas.ferreira@email.com,11999990014

In [ ]:
df[df["telefone"].duplicated(keep=False)]  # Quais registros possuem telefones duplicados na nossa base?

,id,nome,idade,cidade,especialidade,status,email,telefone
3,4,Mariana Silva,35.0,valinhos,pediatria,concluido,mariana.silva@email.com,11999990004
21,21,Mariana Silva,35.0,valinhos,pediatria,concluido,mariana.silva@email.com,11999990004

In [ ]:
df = df.drop_duplicates(subset="email")  # Remove registros duplicados considerando o email como identificador

In [ ]:
df.drop_duplicates(subset="email", keep="first")  # Remove duplicados pelo email mantendo apenas o primeiro registro

,id,nome,idade,cidade,especialidade,status,email,telefone
0,1,Bruno Lima,30.0,vinhedo,clinico geral,concluido,bruno.lima@email.com,11999990001
1,2,Ana Souza,37.0,campinas,cardiologia,agendado,ana.souza@email.com,11999990002
2,3,Carlos Mendes,40.0,jundiai,ortopedia,cancelado,carlos.mendes@email.com,11999990003
3,4,Mariana Silva,35.0,valinhos,pediatria,concluido,mariana.silva@email.com,11999990004
4,5,Joao Santos,52.0,campinas,cardiologia,concluido,joao.santos@email.com,11999990005
6,6,Pedro Oliveira,28.0,campinas,cardiologia,concluido,pedro.oliveira@email.com,11999990006
7,7,Juliana Costa,45.0,campinas,cardiologia,agendado,juliana.costa@email.com,11999990007
8,8,Marcos Pereira,67.0,campinas,ortopedia,cancelado,marcos.pereira@email.com,11999990008
9,9,Fernanda Alves,29.0,vinhedo,dermatologia,concluido,fernanda.alves@email.com,11999990009
10,10,Rafael Souza,37.0,jundiai,cardiologia,agendado,rafael.souza@email.com,11999990010
11,11,Patricia Lima,38.0,campinas,pediatria,concluido,patricia.lima@email.com,11999990011
12,12,Gabriel Santos,NaN,valinhos,ortopedia,concluido,gabriel.santos@email.com,11999990012
13,13,Beatriz Oliveira,22.0,vinhedo,dermatologia,cancelado,beatriz.oliveira@email.com,11999990013
14,14,Lucas Ferreira,41.0,campinas,cardiologia,agendado,lucas.ferreira@email.com,11999990014
15,15,Amanda Rodrigues,34.0,campinas,pediatria,concluido,amanda.rodrigues@email.com,11999990015
16,16,Diego Martins,39.0,jundiai,ortopedia,concluido,diego.martins@email.com,11999990016
17,17,Carolina Gomes,27.0,valinhos,dermatologia,cancelado,carolina.gomes@email.com,11999990017
18,18,Thiago Alves,63.0,campinas,cardiologia,concluido,thiago.alves@email.com,11999990018
19,19,Julio Santos,NaN,vinhedo,clinico geral,agendado,julio.santos@email.com,11999990019
20,20,Renata Costa,31.0,campinas,pediatria,concluido,renata.costa@email.com,11999990020
21,21,Mariana Silva,35.0,valinhos,pediatria,concluido,mariana.silva@email.com,11999990004
22,22,Roberto Lima,49.0,campinas,cardiologia,cancelado,roberto.lima@email.com,11999990021
23,23,Isabela Mendes,26.0,vinhedo,dermatologia,agendado,isabela.mendes@email.com,11999990022
24,24,Daniel Souza,58.0,campinas,cardiologia,concluido,daniel.souza@email.com,11999990023
25,25,Vanessa Oliveira,37.0,valinhos,pediatria,agendado,vanessa.oliveira@email.com,11999990024
26,26,Andre Pereira,36.0,campinas,ortopedia,concluido,andre.pereira@email.com,11999990025
27,27,Paula Fernandes,43.0,vinhedo,dermatologia,concluido,paula.fernandes@email.com,11999990026
28,28,Mateus Costa,19.0,campinas,clinico geral,cancelado,mateus.costa@email.com,11999990027
30,30,Joana Alves,33.0,valinhos,pediatria,concluido,joana.alves@email.com,11999990028

In [ ]:
df["cidade"].value_counts()  # Qual cidade possui mais registros na nossa base?

cidade
campinas    14
vinhedo      6
valinhos     6
jundiai      3
Name: count, dtype: int64

In [ ]:
df["especialidade"].value_counts()  # Qual especialidade possui mais registros na nossa base?

especialidade
cardiologia      9
pediatria        7
ortopedia        5
dermatologia     5
clinico geral    3
Name: count, dtype: int64

In [ ]:
df["status"].value_counts()  # Qual é o status mais frequente na nossa base?

status
concluido    16
agendado      7
cancelado     6
Name: count, dtype: int64

In [ ]:
df["status"].value_counts()["cancelado"]  # Quantos registros possuem o status cancelado?

np.int64(6)

In [ ]:
df["cidade"].value_counts().idxmax()  # Qual é a cidade com a maior quantidade de registros?

'campinas'

In [ ]:
df["cidade"].value_counts().max()  # Qual é a maior quantidade de registros encontrada em uma cidade?

np.int64(14)

In [ ]:
print("Atendimentos por cidade:")  # Exibe o título da análise de atendimentos por cidade
df["cidade"].value_counts()  # Quantos atendimentos existem em cada cidade?

Atendimentos por cidade:

cidade
campinas    14
vinhedo      6
valinhos     6
jundiai      3
Name: count, dtype: int64

In [ ]:
print("Atendimentos por especialidade:")  # Exibe o título da análise de atendimentos por especialidade
df["especialidade"].value_counts()  # Quantos atendimentos existem em cada especialidade?

Atendimentos por especialidade:

especialidade
cardiologia      9
pediatria        7
ortopedia        5
dermatologia     5
clinico geral    3
Name: count, dtype: int64

In [ ]:
print("Atendimentos por status:")  # Exibe o título da análise de atendimentos por status
df["status"].value_counts()  # Quantos atendimentos existem em cada status?

Atendimentos por status:

status
concluido    16
agendado      7
cancelado     6
Name: count, dtype: int64

In [ ]:
df["status"].value_counts()  # Qual é o status mais frequente?

status
concluido    16
agendado      7
cancelado     6
Name: count, dtype: int64

In [51]:
df.groupby("cidade")["idade"].mean()  # Qual é a idade média dos pacientes em cada cidade?

cidade
campinas    42.714286
jundiai     38.666667
valinhos    33.400000
vinhedo     30.000000
Name: idade, dtype: float64

In [53]:
df.groupby("cidade")["idade"].count()  # Quantos pacientes possuem idade registrada em cada cidade?

cidade
campinas    14
jundiai      3
valinhos     5
vinhedo      5
Name: idade, dtype: int64

In [54]:
df.groupby("especialidade")["idade"].mean()  # Qual é a idade média dos pacientes em cada especialidade?

especialidade
cardiologia      45.555556
clinico geral    24.500000
dermatologia     29.400000
ortopedia        45.500000
pediatria        34.714286
Name: idade, dtype: float64

In [55]:
df.groupby(["cidade", "status"]).size()  # Quantos atendimentos existem em cada cidade para cada status?

cidade    status
campinas  agendado     3
          cancelado    3
          concluido    8
jundiai   agendado     1
          cancelado    1
          concluido    1
valinhos  agendado     1
          cancelado    1
          concluido    4
vinhedo   agendado     2
          cancelado    1
          concluido    3
dtype: int64

In [56]:
df.groupby(["cidade", "status"]).size().unstack(fill_value=0)  # Como os atendimentos estão distribuídos por cidade e status?

status    agendado  cancelado  concluido
cidade
campinas         3          3          8
jundiai          1          1          1
valinhos         1          1          4
vinhedo          2          1          3

In [57]:
df.groupby("cidade")["idade"].agg(["count", "mean", "min", "max"])  # Qual é o resumo das idades dos pacientes em cada cidade?

          count       mean   min   max
cidade
campinas     14  42.714286  19.0  67.0
jundiai       3  38.666667  37.0  40.0
valinhos      5  33.400000  27.0  37.0
vinhedo       5  30.000000  22.0  43.0

In [58]:
df.groupby("cidade")["idade"].agg(["count", "mean", "min", "max"])  # Qual é o resumo das idades dos pacientes em cada cidade?

          count       mean   min   max
cidade
campinas     14  42.714286  19.0  67.0
jundiai       3  38.666667  37.0  40.0
valinhos      5  33.400000  27.0  37.0
vinhedo       5  30.000000  22.0  43.0

In [63]:
df["idade"].agg([
    "sum",       # Qual é a soma de todas as idades registradas?
    "mean",      # Qual é a idade média dos pacientes?
    "median",    # Qual é a idade que divide os pacientes ao meio?
    "min",       # Qual é a menor idade registrada?
    "max",       # Qual é a maior idade registrada?
    "std",       # Qual é o nível de variação das idades em relação à média?
    "var"        # Qual é a variância das idades registradas?
])  # Quais são as principais estatísticas da distribuição das idades?

sum       1031.000000
mean        38.185185
median      37.000000
min         19.000000
max         67.000000
std         11.622382
var        135.079772
Name: idade, dtype: float64

In [61]:
df["idade"].agg([
    "count",      # Quantos pacientes possuem idade registrada?
    "mean",       # Qual é a idade média?
    "median",     # Qual é a idade central?
    "min",        # Qual é a menor idade?
    "max",        # Qual é a maior idade?
    "std"         # Quanto as idades variam em relação à média?
])  # Qual é o resumo principal das idades dos pacientes?

count     27.000000
mean      38.185185
median    37.000000
min       19.000000
max       67.000000
std       11.622382
Name: idade, dtype: float64

In [64]:
df.groupby("cidade")["idade"].mean().sort_values()  # Qual cidade possui a menor idade média dos pacientes?

cidade
vinhedo     30.000000
valinhos    33.400000
jundiai     38.666667
campinas    42.714286
Name: idade, dtype: float64

In [65]:
df.groupby("cidade")["idade"].mean().sort_values(ascending=False)  # Qual cidade possui a maior idade média dos pacientes?

cidade
campinas    42.714286
jundiai     38.666667
valinhos    33.400000
vinhedo     30.000000
Name: idade, dtype: float64

In [66]:
df.sort_values("idade")  # Quais são os registros ordenados da menor para a maior idade?

,id,nome,idade,cidade,especialidade,status,email,telefone
28,28,Mateus Costa,19.0,campinas,clinico geral,cancelado,mateus.costa@email.com,11999990027
13,13,Beatriz Oliveira,22.0,vinhedo,dermatologia,cancelado,beatriz.oliveira@email.com,11999990013
23,23,Isabela Mendes,26.0,vinhedo,dermatologia,agendado,isabela.mendes@email.com,11999990022
17,17,Carolina Gomes,27.0,valinhos,dermatologia,cancelado,carolina.gomes@email.com,11999990017
6,6,Pedro Oliveira,28.0,campinas,cardiologia,concluido,pedro.oliveira@email.com,11999990006
9,9,Fernanda Alves,29.0,vinhedo,dermatologia,concluido,fernanda.alves@email.com,11999990009
0,1,Bruno Lima,30.0,vinhedo,clinico geral,concluido,bruno.lima@email.com,11999990001
20,20,Renata Costa,31.0,campinas,pediatria,concluido,renata.costa@email.com,11999990020
30,30,Joana Alves,33.0,valinhos,pediatria,concluido,joana.alves@email.com,11999990028
15,15,Amanda Rodrigues,34.0,campinas,pediatria,concluido,amanda.rodrigues@email.com,11999990015
3,4,Mariana Silva,35.0,valinhos,pediatria,concluido,mariana.silva@email.com,11999990004
21,21,Mariana Silva,35.0,valinhos,pediatria,concluido,mariana.silva@email.com,11999990004
26,26,Andre Pereira,36.0,campinas,ortopedia,concluido,andre.pereira@email.com,11999990025
25,25,Vanessa Oliveira,37.0,valinhos,pediatria,agendado,vanessa.oliveira@email.com,11999990024
10,10,Rafael Souza,37.0,jundiai,cardiologia,agendado,rafael.souza@email.com,11999990010
1,2,Ana Souza,37.0,campinas,cardiologia,agendado,ana.souza@email.com,11999990002
11,11,Patricia Lima,38.0,campinas,pediatria,concluido,patricia.lima@email.com,11999990011
16,16,Diego Martins,39.0,jundiai,ortopedia,concluido,diego.martins@email.com,11999990016
2,3,Carlos Mendes,40.0,jundiai,ortopedia,cancelado,carlos.mendes@email.com,11999990003
14,14,Lucas Ferreira,41.0,campinas,cardiologia,agendado,lucas.ferreira@email.com,11999990014
27,27,Paula Fernandes,43.0,vinhedo,dermatologia,concluido,paula.fernandes@email.com,11999990026
7,7,Juliana Costa,45.0,campinas,cardiologia,agendado,juliana.costa@email.com,11999990007
22,22,Roberto Lima,49.0,campinas,cardiologia,cancelado,roberto.lima@email.com,11999990021
4,5,Joao Santos,52.0,campinas,cardiologia,concluido,joao.santos@email.com,11999990005
24,24,Daniel Souza,58.0,campinas,cardiologia,concluido,daniel.souza@email.com,11999990023
18,18,Thiago Alves,63.0,campinas,cardiologia,concluido,thiago.alves@email.com,11999990018
8,8,Marcos Pereira,67.0,campinas,ortopedia,cancelado,marcos.pereira@email.com,11999990008
12,12,Gabriel Santos,NaN,valinhos,ortopedia,concluido,gabriel.santos@email.com,11999990012
19,19,Julio Santos,NaN,vinhedo,clinico geral,agendado,julio.santos@email.com,11999990019

In [67]:
df.sort_values("idade", ascending=False)  # Quais são os registros ordenados da maior para a menor idade?

,id,nome,idade,cidade,especialidade,status,email,telefone
8,8,Marcos Pereira,67.0,campinas,ortopedia,cancelado,marcos.pereira@email.com,11999990008
18,18,Thiago Alves,63.0,campinas,cardiologia,concluido,thiago.alves@email.com,11999990018
24,24,Daniel Souza,58.0,campinas,cardiologia,concluido,daniel.souza@email.com,11999990023
4,5,Joao Santos,52.0,campinas,cardiologia,concluido,joao.santos@email.com,11999990005
22,22,Roberto Lima,49.0,campinas,cardiologia,cancelado,roberto.lima@email.com,11999990021
7,7,Juliana Costa,45.0,campinas,cardiologia,agendado,juliana.costa@email.com,11999990007
27,27,Paula Fernandes,43.0,vinhedo,dermatologia,concluido,paula.fernandes@email.com,11999990026
14,14,Lucas Ferreira,41.0,campinas,cardiologia,agendado,lucas.ferreira@email.com,11999990014
2,3,Carlos Mendes,40.0,jundiai,ortopedia,cancelado,carlos.mendes@email.com,11999990003
16,16,Diego Martins,39.0,jundiai,ortopedia,concluido,diego.martins@email.com,11999990016
11,11,Patricia Lima,38.0,campinas,pediatria,concluido,patricia.lima@email.com,11999990011
1,2,Ana Souza,37.0,campinas,cardiologia,agendado,ana.souza@email.com,11999990002
10,10,Rafael Souza,37.0,jundiai,cardiologia,agendado,rafael.souza@email.com,11999990010
25,25,Vanessa Oliveira,37.0,valinhos,pediatria,agendado,vanessa.oliveira@email.com,11999990024
26,26,Andre Pereira,36.0,campinas,ortopedia,concluido,andre.pereira@email.com,11999990025
21,21,Mariana Silva,35.0,valinhos,pediatria,concluido,mariana.silva@email.com,11999990004
3,4,Mariana Silva,35.0,valinhos,pediatria,concluido,mariana.silva@email.com,11999990004
15,15,Amanda Rodrigues,34.0,campinas,pediatria,concluido,amanda.rodrigues@email.com,11999990015
30,30,Joana Alves,33.0,valinhos,pediatria,concluido,joana.alves@email.com,11999990028
20,20,Renata Costa,31.0,campinas,pediatria,concluido,renata.costa@email.com,11999990020
0,1,Bruno Lima,30.0,vinhedo,clinico geral,concluido,bruno.lima@email.com,11999990001
9,9,Fernanda Alves,29.0,vinhedo,dermatologia,concluido,fernanda.alves@email.com,11999990009
6,6,Pedro Oliveira,28.0,campinas,cardiologia,concluido,pedro.oliveira@email.com,11999990006
17,17,Carolina Gomes,27.0,valinhos,dermatologia,cancelado,carolina.gomes@email.com,11999990017
23,23,Isabela Mendes,26.0,vinhedo,dermatologia,agendado,isabela.mendes@email.com,11999990022
13,13,Beatriz Oliveira,22.0,vinhedo,dermatologia,cancelado,beatriz.oliveira@email.com,11999990013
28,28,Mateus Costa,19.0,campinas,clinico geral,cancelado,mateus.costa@email.com,11999990027
12,12,Gabriel Santos,NaN,valinhos,ortopedia,concluido,gabriel.santos@email.com,11999990012
19,19,Julio Santos,NaN,vinhedo,clinico geral,agendado,julio.santos@email.com,11999990019

In [68]:
df.sort_values(["cidade", "idade"])  # Como os pacientes estão ordenados por cidade e depois por idade?

,id,nome,idade,cidade,especialidade,status,email,telefone
28,28,Mateus Costa,19.0,campinas,clinico geral,cancelado,mateus.costa@email.com,11999990027
6,6,Pedro Oliveira,28.0,campinas,cardiologia,concluido,pedro.oliveira@email.com,11999990006
20,20,Renata Costa,31.0,campinas,pediatria,concluido,renata.costa@email.com,11999990020
15,15,Amanda Rodrigues,34.0,campinas,pediatria,concluido,amanda.rodrigues@email.com,11999990015
26,26,Andre Pereira,36.0,campinas,ortopedia,concluido,andre.pereira@email.com,11999990025
1,2,Ana Souza,37.0,campinas,cardiologia,agendado,ana.souza@email.com,11999990002
11,11,Patricia Lima,38.0,campinas,pediatria,concluido,patricia.lima@email.com,11999990011
14,14,Lucas Ferreira,41.0,campinas,cardiologia,agendado,lucas.ferreira@email.com,11999990014
7,7,Juliana Costa,45.0,campinas,cardiologia,agendado,juliana.costa@email.com,11999990007
22,22,Roberto Lima,49.0,campinas,cardiologia,cancelado,roberto.lima@email.com,11999990021
4,5,Joao Santos,52.0,campinas,cardiologia,concluido,joao.santos@email.com,11999990005
24,24,Daniel Souza,58.0,campinas,cardiologia,concluido,daniel.souza@email.com,11999990023
18,18,Thiago Alves,63.0,campinas,cardiologia,concluido,thiago.alves@email.com,11999990018
8,8,Marcos Pereira,67.0,campinas,ortopedia,cancelado,marcos.pereira@email.com,11999990008
10,10,Rafael Souza,37.0,jundiai,cardiologia,agendado,rafael.souza@email.com,11999990010
16,16,Diego Martins,39.0,jundiai,ortopedia,concluido,diego.martins@email.com,11999990016
2,3,Carlos Mendes,40.0,jundiai,ortopedia,cancelado,carlos.mendes@email.com,11999990003
17,17,Carolina Gomes,27.0,valinhos,dermatologia,cancelado,carolina.gomes@email.com,11999990017
30,30,Joana Alves,33.0,valinhos,pediatria,concluido,joana.alves@email.com,11999990028
3,4,Mariana Silva,35.0,valinhos,pediatria,concluido,mariana.silva@email.com,11999990004
21,21,Mariana Silva,35.0,valinhos,pediatria,concluido,mariana.silva@email.com,11999990004
25,25,Vanessa Oliveira,37.0,valinhos,pediatria,agendado,vanessa.oliveira@email.com,11999990024
12,12,Gabriel Santos,NaN,valinhos,ortopedia,concluido,gabriel.santos@email.com,11999990012
13,13,Beatriz Oliveira,22.0,vinhedo,dermatologia,cancelado,beatriz.oliveira@email.com,11999990013
23,23,Isabela Mendes,26.0,vinhedo,dermatologia,agendado,isabela.mendes@email.com,11999990022
9,9,Fernanda Alves,29.0,vinhedo,dermatologia,concluido,fernanda.alves@email.com,11999990009
0,1,Bruno Lima,30.0,vinhedo,clinico geral,concluido,bruno.lima@email.com,11999990001
27,27,Paula Fernandes,43.0,vinhedo,dermatologia,concluido,paula.fernandes@email.com,11999990026
19,19,Julio Santos,NaN,vinhedo,clinico geral,agendado,julio.santos@email.com,11999990019

In [69]:
df.sort_values(["cidade", "idade"], ascending=[True, False])  # Como ordenar as cidades em ordem crescente e as idades em ordem decrescente?

,id,nome,idade,cidade,especialidade,status,email,telefone
8,8,Marcos Pereira,67.0,campinas,ortopedia,cancelado,marcos.pereira@email.com,11999990008
18,18,Thiago Alves,63.0,campinas,cardiologia,concluido,thiago.alves@email.com,11999990018
24,24,Daniel Souza,58.0,campinas,cardiologia,concluido,daniel.souza@email.com,11999990023
4,5,Joao Santos,52.0,campinas,cardiologia,concluido,joao.santos@email.com,11999990005
22,22,Roberto Lima,49.0,campinas,cardiologia,cancelado,roberto.lima@email.com,11999990021
7,7,Juliana Costa,45.0,campinas,cardiologia,agendado,juliana.costa@email.com,11999990007
14,14,Lucas Ferreira,41.0,campinas,cardiologia,agendado,lucas.ferreira@email.com,11999990014
11,11,Patricia Lima,38.0,campinas,pediatria,concluido,patricia.lima@email.com,11999990011
1,2,Ana Souza,37.0,campinas,cardiologia,agendado,ana.souza@email.com,11999990002
26,26,Andre Pereira,36.0,campinas,ortopedia,concluido,andre.pereira@email.com,11999990025
15,15,Amanda Rodrigues,34.0,campinas,pediatria,concluido,amanda.rodrigues@email.com,11999990015
20,20,Renata Costa,31.0,campinas,pediatria,concluido,renata.costa@email.com,11999990020
6,6,Pedro Oliveira,28.0,campinas,cardiologia,concluido,pedro.oliveira@email.com,11999990006
28,28,Mateus Costa,19.0,campinas,clinico geral,cancelado,mateus.costa@email.com,11999990027
2,3,Carlos Mendes,40.0,jundiai,ortopedia,cancelado,carlos.mendes@email.com,11999990003
16,16,Diego Martins,39.0,jundiai,ortopedia,concluido,diego.martins@email.com,11999990016
10,10,Rafael Souza,37.0,jundiai,cardiologia,agendado,rafael.souza@email.com,11999990010
25,25,Vanessa Oliveira,37.0,valinhos,pediatria,agendado,vanessa.oliveira@email.com,11999990024
3,4,Mariana Silva,35.0,valinhos,pediatria,concluido,mariana.silva@email.com,11999990004
21,21,Mariana Silva,35.0,valinhos,pediatria,concluido,mariana.silva@email.com,11999990004
30,30,Joana Alves,33.0,valinhos,pediatria,concluido,joana.alves@email.com,11999990028
17,17,Carolina Gomes,27.0,valinhos,dermatologia,cancelado,carolina.gomes@email.com,11999990017
12,12,Gabriel Santos,NaN,valinhos,ortopedia,concluido,gabriel.santos@email.com,11999990012
27,27,Paula Fernandes,43.0,vinhedo,dermatologia,concluido,paula.fernandes@email.com,11999990026
0,1,Bruno Lima,30.0,vinhedo,clinico geral,concluido,bruno.lima@email.com,11999990001
9,9,Fernanda Alves,29.0,vinhedo,dermatologia,concluido,fernanda.alves@email.com,11999990009
23,23,Isabela Mendes,26.0,vinhedo,dermatologia,agendado,isabela.mendes@email.com,11999990022
13,13,Beatriz Oliveira,22.0,vinhedo,dermatologia,cancelado,beatriz.oliveira@email.com,11999990013
19,19,Julio Santos,NaN,vinhedo,clinico geral,agendado,julio.santos@email.com,11999990019

In [70]:
df.groupby("cidade")["idade"].agg(["count", "mean", "min", "max"]).sort_values("mean", ascending=False)  # Quais cidades possuem as maiores idades médias dos pacientes?

          count       mean   min   max
cidade
campinas     14  42.714286  19.0  67.0
jundiai       3  38.666667  37.0  40.0
valinhos      5  33.400000  27.0  37.0
vinhedo       5  30.000000  22.0  43.0

In [71]:
df[df["idade"] > 50]  # Quais pacientes possuem mais de 50 anos?

,id,nome,idade,cidade,especialidade,status,email,telefone
4,5,Joao Santos,52.0,campinas,cardiologia,concluido,joao.santos@email.com,11999990005
8,8,Marcos Pereira,67.0,campinas,ortopedia,cancelado,marcos.pereira@email.com,11999990008
18,18,Thiago Alves,63.0,campinas,cardiologia,concluido,thiago.alves@email.com,11999990018
24,24,Daniel Souza,58.0,campinas,cardiologia,concluido,daniel.souza@email.com,11999990023

In [72]:
df.loc[df["idade"] > 50, ["nome", "idade", "cidade"]]  # Quais são os pacientes com mais de 50 anos e suas respectivas cidades?

              nome  idade    cidade
4      Joao Santos   52.0  campinas
8   Marcos Pereira   67.0  campinas
18    Thiago Alves   63.0  campinas
24    Daniel Souza   58.0  campinas

In [73]:
df.loc[df["status"] == "cancelado"]  # Quais atendimentos possuem status cancelado?

,id,nome,idade,cidade,especialidade,status,email,telefone
2,3,Carlos Mendes,40.0,jundiai,ortopedia,cancelado,carlos.mendes@email.com,11999990003
8,8,Marcos Pereira,67.0,campinas,ortopedia,cancelado,marcos.pereira@email.com,11999990008
13,13,Beatriz Oliveira,22.0,vinhedo,dermatologia,cancelado,beatriz.oliveira@email.com,11999990013
17,17,Carolina Gomes,27.0,valinhos,dermatologia,cancelado,carolina.gomes@email.com,11999990017
22,22,Roberto Lima,49.0,campinas,cardiologia,cancelado,roberto.lima@email.com,11999990021
28,28,Mateus Costa,19.0,campinas,clinico geral,cancelado,mateus.costa@email.com,11999990027

In [74]:
df.loc[df["status"] == "cancelado", ["nome", "especialidade", "status"]]  # Quais pacientes possuem atendimentos cancelados e quais são suas especialidades?

                nome  especialidade     status
2      Carlos Mendes      ortopedia  cancelado
8     Marcos Pereira      ortopedia  cancelado
13  Beatriz Oliveira   dermatologia  cancelado
17    Carolina Gomes   dermatologia  cancelado
22      Roberto Lima    cardiologia  cancelado
28      Mateus Costa  clinico geral  cancelado

In [75]:
df.loc[(df["idade"] > 50) & (df["status"] == "cancelado")]  # Quais pacientes com mais de 50 anos possuem atendimentos cancelados?

,id,nome,idade,cidade,especialidade,status,email,telefone
8,8,Marcos Pereira,67.0,campinas,ortopedia,cancelado,marcos.pereira@email.com,11999990008

In [76]:
df.loc[(df["cidade"] == "campinas") | (df["cidade"] == "vinhedo")]  # Quais pacientes são de Campinas ou Vinhedo?

,id,nome,idade,cidade,especialidade,status,email,telefone
0,1,Bruno Lima,30.0,vinhedo,clinico geral,concluido,bruno.lima@email.com,11999990001
1,2,Ana Souza,37.0,campinas,cardiologia,agendado,ana.souza@email.com,11999990002
4,5,Joao Santos,52.0,campinas,cardiologia,concluido,joao.santos@email.com,11999990005
6,6,Pedro Oliveira,28.0,campinas,cardiologia,concluido,pedro.oliveira@email.com,11999990006
7,7,Juliana Costa,45.0,campinas,cardiologia,agendado,juliana.costa@email.com,11999990007
8,8,Marcos Pereira,67.0,campinas,ortopedia,cancelado,marcos.pereira@email.com,11999990008
9,9,Fernanda Alves,29.0,vinhedo,dermatologia,concluido,fernanda.alves@email.com,11999990009
11,11,Patricia Lima,38.0,campinas,pediatria,concluido,patricia.lima@email.com,11999990011
13,13,Beatriz Oliveira,22.0,vinhedo,dermatologia,cancelado,beatriz.oliveira@email.com,11999990013
14,14,Lucas Ferreira,41.0,campinas,cardiologia,agendado,lucas.ferreira@email.com,11999990014
15,15,Amanda Rodrigues,34.0,campinas,pediatria,concluido,amanda.rodrigues@email.com,11999990015
18,18,Thiago Alves,63.0,campinas,cardiologia,concluido,thiago.alves@email.com,11999990018
19,19,Julio Santos,NaN,vinhedo,clinico geral,agendado,julio.santos@email.com,11999990019
20,20,Renata Costa,31.0,campinas,pediatria,concluido,renata.costa@email.com,11999990020
22,22,Roberto Lima,49.0,campinas,cardiologia,cancelado,roberto.lima@email.com,11999990021
23,23,Isabela Mendes,26.0,vinhedo,dermatologia,agendado,isabela.mendes@email.com,11999990022
24,24,Daniel Souza,58.0,campinas,cardiologia,concluido,daniel.souza@email.com,11999990023
26,26,Andre Pereira,36.0,campinas,ortopedia,concluido,andre.pereira@email.com,11999990025
27,27,Paula Fernandes,43.0,vinhedo,dermatologia,concluido,paula.fernandes@email.com,11999990026
28,28,Mateus Costa,19.0,campinas,clinico geral,cancelado,mateus.costa@email.com,11999990027

In [77]:
df.loc[(df["idade"] >= 18) & (df["idade"] <= 30), ["nome", "idade", "cidade"]]  # Quais são os pacientes com idade entre 18 e 30 anos e suas respectivas cidades?

                nome  idade    cidade
0         Bruno Lima   30.0   vinhedo
6     Pedro Oliveira   28.0  campinas
9     Fernanda Alves   29.0   vinhedo
13  Beatriz Oliveira   22.0   vinhedo
17    Carolina Gomes   27.0  valinhos
23    Isabela Mendes   26.0   vinhedo
28      Mateus Costa   19.0  campinas

In [78]:
df.loc[(df["idade"] < 0) | (df["idade"] > 100), "idade"] = pd.NA  # Substitui idades inválidas por valores ausentes

In [79]:
df["faixa_etaria"] = "adulto"  # Define inicialmente todos os pacientes como adultos

In [80]:
df.loc[df["idade"] < 18, "faixa_etaria"] = "menor de idade"  # Classifica pacientes menores de 18 anos

In [81]:
df.loc[df["idade"] >= 60, "faixa_etaria"] = "idoso"  # Classifica pacientes com 60 anos ou mais

In [82]:
df["faixa_etaria"].value_counts()  # Quantos pacientes existem em cada faixa etária?

faixa_etaria
adulto    27
idoso      2
Name: count, dtype: int64

In [83]:
df.groupby(["faixa_etaria", "status"]).size()  # Quantos atendimentos existem por faixa etária e status?

faixa_etaria  status
adulto        agendado      7
              cancelado     5
              concluido    15
idoso         cancelado     1
              concluido     1
dtype: int64

In [84]:
df.groupby(["faixa_etaria", "status"]).size().unstack(fill_value=0)  # Como os atendimentos estão distribuídos por faixa etária e status?

status        agendado  cancelado  concluido
faixa_etaria
adulto               7          5         15
idoso                0          1          1